import * as fs from 'node:fs';
import * as path from 'node:path';
import { safeJsonParse, writeTextAtomic } from '../utils/files';
import { DEFAULT_TOKENS, type DesignNode, type DesignPage, type DesignTokens } from './designModel';

export interface CodegenResult {
  files: string[];
  warnings: string[];
}

/**
 * OpenDesign → real code (P4). Deterministic generator: reads design/ and
 * emits an editable React codebase + CSS custom properties into
 * `src/website/generated/`. In the full pipeline a system agent reviews and
 * refines this output before commit; the generator guarantees the design is
 * always representable as real, runnable code.
 */
export class CodegenEngine {
  generate(empireRoot: string): CodegenResult {
    const designDir = path.join(empireRoot, 'design');
    const outDir = path.join(empireRoot, 'src', 'website', 'generated');
    const files: string[] = [];
    const warnings: string[] = [];

    const tokens = safeJsonParse<DesignTokens>(path.join(designDir, 'tokens.json'), DEFAULT_TOKENS);
    const pages = this.loadPages(designDir);

    fs.mkdirSync(path.join(outDir, 'pages'), { recursive: true });

    files.push(this.write(path.join(outDir, 'tokens.css'), this.tokensToCss(tokens)));

    const components = new Set<string>();
    for (const page of pages) {
      for (const node of page.nodes) {
        this.collectTypes(node, components);
      }
    }

    files.push(this.write(path.join(outDir, 'components.jsx'), this.componentsJsx([...components])));
    files.push(this.write(path.join(outDir, 'theme.js'), this.themeJs(tokens)));

    for (const page of pages) {
      const file = `${this.kebab(page.name || page.id)}.jsx`;
      files.push(this.write(path.join(outDir, 'pages', file), this.pageJsx(page)));
    }

    const index = [
      `// Generated by OpenDesign — do not hand-edit; edit design/ instead.`,
      `import { ${[...components].map((c) => this.typeToComponent(c)).join(', ')} } from './components.jsx';`,
      pages.length ? `import { ${pages.map((p) => `${this.pascal(p.name || p.id)}Page`).join(', ')} } from './pages';` : '',
      `import './tokens.css';`,
      '',
      'export { tokens as designTokens } from "./theme.js";',
      `export { ${[...components].map((c) => this.typeToComponent(c)).join(', ')} };`,
      ''
    ].filter((l) => l !== '').join('\n');
    files.push(this.write(path.join(outDir, 'index.js'), index));

    return { files, warnings };
  }

  tokensToCss(tokens: DesignTokens): string {
    const lines = ['/* Generated by OpenDesign from design/tokens.json. */', ':root {'];
    for (const [name, value] of Object.entries(tokens.colors)) {
      lines.push(`  --color-${this.kebab(name)}: ${value};`);
    }
    lines.push(`  --font-heading: ${tokens.fonts.heading};`);
    lines.push(`  --font-body: ${tokens.fonts.body};`);
    for (const [name, value] of Object.entries(tokens.spacing)) {
      lines.push(`  --space-${name}: ${value};`);
    }
    for (const [name, value] of Object.entries(tokens.radii)) {
      lines.push(`  --radius-${name}: ${value};`);
    }
    for (const [name, value] of Object.entries(tokens.shadows)) {
      lines.push(`  --shadow-${name}: ${value};`);
    }
    lines.push('}', '');
    lines.push('body { margin: 0; font-family: var(--font-body); color: var(--color-text); background: var(--color-background); }');
    lines.push('h1, h2, h3, h4 { font-family: var(--font-heading); }');
    lines.push('button { font-family: inherit; }');
    return lines.join('\n');
  }

  private componentsJsx(types: string[]): string {
    const lines = [
      '// Generated by OpenDesign from design/pages/*.json — real, editable React.',
      'import React from "react";',
      '',
      'const styles = {',
      '  button: (variant) => ({',
      '    padding: "var(--space-sm) var(--space-md)",',
      '    borderRadius: "var(--radius-md)",',
      '    border: "1px solid var(--color-border)",',
      '    cursor: "pointer",',
      '    fontSize: "1rem",',
      '    ...(variant === "primary" && { background: "var(--color-primary)", color: "#fff", borderColor: "var(--color-primary)" }),',
      '    ...(variant === "secondary" && { background: "var(--color-secondary)", color: "#fff", borderColor: "var(--color-secondary)" }),',
      '    ...(variant === "ghost" && { background: "transparent" })',
      '  }),',
      '  card: {',
      '    background: "var(--color-surface)",',
      '    border: "1px solid var(--color-border)",',
      '    borderRadius: "var(--radius-lg)",',
      '    padding: "var(--space-lg)",',
      '    boxShadow: "var(--shadow-md)"',
      '  },',
      '  input: {',
      '    padding: "var(--space-sm)",',
      '    border: "1px solid var(--color-border)",',
      '    borderRadius: "var(--radius-md)",',
      '    fontSize: "1rem",',
      '    width: "100%",',
      '    boxSizing: "border-box"',
      '  }',
      '};',
      ''
    ];
    const components: Record<string, string> = {
      box: '({ children, ...props }) => <div style={props} {...props}>{children}</div>',
      text: '({ text, ...props }) => <p style={props}>{text}</p>',
      heading: '({ text, level = "h2", ...props }) => { const Tag = level; return <Tag style={props}>{text}</Tag>; }',
      button: '({ text, variant = "primary", ...props }) => <button style={{ ...styles.button(variant), ...props.style }} onClick={props.onClick}>{text}</button>',
      input: '({ placeholder, ...props }) => <input style={styles.input} placeholder={placeholder} {...props} />',
      card: '({ children, ...props }) => <div style={{ ...styles.card, ...props.style }} {...props}>{children}</div>',
      navbar: '({ title, children, ...props }) => <nav style={{ display: "flex", gap: "var(--space-md)", alignItems: "center", padding: "var(--space-md)", background: "var(--color-surface)", borderBottom: "1px solid var(--color-border)", ...props.style }}>{title && <strong style={{ fontFamily: "var(--font-heading)" }}>{title}</strong>}{children}</nav>',
      image: '({ src, alt, ...props }) => <img src={src} alt={alt} style={{ maxWidth: "100%", borderRadius: "var(--radius-md)", ...props.style }} {...props} />',
      form: '({ children, ...props }) => <form style={{ display: "flex", flexDirection: "column", gap: "var(--space-md)", ...props.style }} {...props}>{children}</form>',
      list: '({ items, ...props }) => { const entries = String(items || "").split("\\n").filter(Boolean); return <ul {...props}>{entries.map((item, i) => <li key={i}>{item}</li>)}</ul>; }'
    };
    for (const type of types) {
      const name = this.typeToComponent(type);
      const fn = components[type];
      if (fn) lines.push(`export const ${name} = ${fn};`);
    }
    return lines.join('\n');
  }

  private themeJs(tokens: DesignTokens): string {
    return `// Generated by OpenDesign from design/tokens.json.\nexport const tokens = ${JSON.stringify(tokens, null, 2)};\n`;
  }

  private pageJsx(page: DesignPage): string {
    const componentName = `${this.pascal(page.name || page.id)}Page`;
    const lines = [
      '// Generated by OpenDesign from design/pages/*.json.',
      'import React from "react";',
      `import { ${this.uniqueTypes(page).map((t) => this.typeToComponent(t)).join(', ')} } from "../components.jsx";`,
      '',
      `export function ${componentName}() {`,
      '  return (',
      '    <>',
      ...this.renderNodes(page, '', '      '),
      '    </>',
      '  );',
      '}',
      ''
    ];
    return lines.join('\n');
  }

  private renderNodes(page: DesignPage, parentId: string, indent: string): string[] {
    const roots = page.nodes.filter((n) => !parentId || n.props.parent === parentId);
    const byParent = new Map<string, DesignNode[]>();
    for (const node of page.nodes) {
      const pid = node.props.parent ?? '';
      if (!byParent.has(pid)) byParent.set(pid, []);
      byParent.get(pid)!.push(node);
    }
    const out: string[] = [];
    const render = (nodes: DesignNode[], depth: number): void => {
      const pad = indent + '  '.repeat(depth);
      for (const node of nodes) {
        const children = byParent.get(node.id) ?? [];
        const props = this.propsToJsx(node);
        const Tag = this.typeToComponent(node.type);
        if (children.length > 0) {
          out.push(`${pad}<${Tag}${props}>`);
          render(children, depth + 1);
          out.push(`${pad}</${Tag}>`);
        } else {
          out.push(`${pad}<${Tag}${props} />`);
        }
      }
    };
    render(roots, 0);
    return out;
  }

  private propsToJsx(node: DesignNode): string {
    const attrs: string[] = [];
    for (const [key, value] of Object.entries(node.props)) {
      if (key === 'parent') continue;
      if (key === 'style' || key === 'onClick') {
        attrs.push(`${key}={${value}}`);
      } else {
        attrs.push(`${key}={${JSON.stringify(value)}}`);
      }
    }
    return attrs.length ? ` ${attrs.join(' ')}` : '';
  }

  private uniqueTypes(page: DesignPage): string[] {
    const types = new Set<string>();
    for (const node of page.nodes) types.add(node.type);
    return [...types];
  }

  private collectTypes(node: DesignNode, out: Set<string>): void {
    out.add(node.type);
  }

  private loadPages(designDir: string): DesignPage[] {
    const pagesDir = path.join(designDir, 'pages');
    if (!fs.existsSync(pagesDir)) return [];
    const pages: DesignPage[] = [];
    for (const entry of fs.readdirSync(pagesDir).sort()) {
      if (!entry.endsWith('.json')) continue;
      const parsed = safeJsonParse<Partial<DesignPage>>(path.join(pagesDir, entry), {});
      if (parsed.id && Array.isArray(parsed.nodes)) {
        pages.push({
          id: parsed.id,
          name: parsed.name ?? parsed.id,
          route: parsed.route ?? '/',
          nodes: parsed.nodes
        });
      }
    }
    return pages;
  }

  private write(filePath: string, content: string): string {
    writeTextAtomic(filePath, content);
    return filePath;
  }

  private kebab(value: string): string {
    return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'page';
  }

  private pascal(value: string): string {
    const parts = value.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
    return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('') || 'Page';
  }

  private typeToComponent(type: string): string {
    return this.pascal(type);
  }
}
